### ISSUE TITLE
initial guess is hardcoded

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/qd_laser_dynamics#21]
If I understand correctly, you're solving your rate equations at steady state, which means your differential equations become a system of (nonlinear) algebraic equations.  You need an initial guess to solve these, which is currently hardcoded in your likelihood function.  That may cause problems when you try to analyze other data sets.  You'll want to come up with a method for finding a good initial guess for the solutions of the rate equations, or allow the user to specify.

**Comment by araun890** [comment]
The initial guesses for the steady state solutions is now included as a user-specified option in the Tutorial file.
