### ISSUE TITLE
Model.py Code Refactoring 

### ISSUE THREAD

**Issue by danielra97** [phys201/qd_laser_dynamics#40]
Not a huge issue, but the current structure of model.py, where you have one class for storing the model data / parameters (`Likelihood`), and another class (`LogLikelihood`) just to compute the log likelihood, seems overly convoluted (using two classes to do what could be done with a single function). Consider revising. 

In addition the description for `LogLikelihood` is wrong (copied from uniform prior).

**Comment by hkwarner** [comment]
Closed with PR #44
