### ISSUE TITLE
Fail installing package

### ISSUE THREAD

**Issue by Yufei1105** [phys201/qd_laser_dynamics#42]
report error:
ERROR: Could not find a version that satisfies the requirement qddynamics
ERROR: No matching distribution found for qddynamics
Not sure if this is because some problem from my end though. Please someone else try this to see if they report the same errors.

**Comment by mudyeh** [comment]
I get the same errors if I try running "pip install qddynamics" or "conda install qddynamics", is that what you mean?

**Comment by dfernandez97** [comment]
After speaking with Vinny, we think this is an issue with out setup.py file. The fix for this is not urgent but will be fixed before the final submission.

**Comment by hkwarner** [comment]
repaired setup file, seems to be installing with no issues now.
